[pytest]

# объявляем маркеры
markers =
    smoke: Основной функционал
    regress: Фулл тесты
    sanity: Выборочный тест нового функционала

# делаем пред.условия
addopts =
    -sv
    # сохраняем результаты тестов в директории
    --alluredir=allure-results
    # чистим от старых результатов нашу директорию
    --clean-alluredir
    #Кол-во допустимых к падению тестов
    --maxfail=5
    # даем реран упавших тестов
    --reruns=2
env =
    STAGE=Stage-1.qa
    BROWSER=Chrome
    URL=https://www.saucedemo.com/
    PYTHON=3.21

