[pytest]

markers =

    smoke: smoker marker
    regression
    profile

addopts =
    -sv
    --only-rerun TimeoutException
    --only-rerun HTTPSConnectionPool
    --only-rerun StaleElementReferenceException
    --only-rerun InvalidSessionIdException